import {
  UserProfile,
  AWSAccount,
  DashboardSummary,
  CostForecastPoint,
  CostBreakdownItem,
  UnitEconomicsMetric,
  CloudResource,
  Recommendation,
  Anomaly,
  RemediationJob,
  ApprovalItem,
  AuditEvent,
  Notification,
  Integration,
  AssistantMessage,
} from '../types';

export const mockUserProfile: UserProfile = {
  id: 'usr_89210',
  name: 'Alex Rivera',
  email: 'alex.rivera@cloudsense.ai',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  role: 'finops_analyst',
  title: 'Lead FinOps Architect',
  department: 'Cloud Operations & Engineering',
  preferences: {
    theme: 'dark',
    density: 'comfortable',
    defaultAccountId: 'acc_aws_prod_01',
    defaultRegion: 'ap-south-1',
    defaultDateRange: '30d',
  },
};

export const mockAWSAccounts: AWSAccount[] = [
  {
    id: 'acc_aws_prod_01',
    accountId: '8492-1049-5830',
    name: 'Production Workloads',
    alias: 'aws-prod-main',
    env: 'production',
    region: 'ap-south-1',
    status: 'connected',
    lastSync: '2 minutes ago',
    resourceCount: 428,
    monthlySpend: 18450,
  },
  {
    id: 'acc_aws_staging_02',
    accountId: '1920-4820-9912',
    name: 'Staging & Integration',
    alias: 'aws-staging-core',
    env: 'staging',
    region: 'us-east-1',
    status: 'connected',
    lastSync: '5 minutes ago',
    resourceCount: 164,
    monthlySpend: 4230,
  },
  {
    id: 'acc_aws_dev_03',
    accountId: '5510-9920-3341',
    name: 'Dev Sandbox',
    alias: 'aws-dev-sandbox',
    env: 'dev',
    region: 'eu-west-1',
    status: 'connected',
    lastSync: '12 minutes ago',
    resourceCount: 92,
    monthlySpend: 1980,
  },
];

export const mockDashboardSummary: DashboardSummary = {
  totalSpend: 24680,
  forecastSpend: 29120,
  potentialSavings: 6840,
  activeAnomaliesCount: 2,
  pendingApprovalsCount: 4,
  healthyResourceCount: 512,
  underutilizedResourceCount: 42,
  oversizedResourceCount: 18,
  idleResourceCount: 14,
  criticalResourceCount: 3,
  spendTrendPercent: 8.4,
  aiInsight: 'Cloud spend increased 8.4% this cycle, primarily driven by unoptimized EC2 instances in ap-south-1 and an idle RDS cluster in production.',
};

export const mockForecastPoints: CostForecastPoint[] = [
  { date: '2026-09-01', actualCost: 780, forecastCost: 775, confidenceLower: 750, confidenceUpper: 800, budgetLimit: 900 },
  { date: '2026-09-03', actualCost: 810, forecastCost: 800, confidenceLower: 775, confidenceUpper: 825, budgetLimit: 900 },
  { date: '2026-09-05', actualCost: 840, forecastCost: 830, confidenceLower: 800, confidenceUpper: 860, budgetLimit: 900 },
  { date: '2026-09-07', actualCost: 825, forecastCost: 820, confidenceLower: 790, confidenceUpper: 850, budgetLimit: 900 },
  { date: '2026-09-09', actualCost: 890, forecastCost: 870, confidenceLower: 840, confidenceUpper: 900, budgetLimit: 900 },
  { date: '2026-09-11', actualCost: 920, forecastCost: 910, confidenceLower: 880, confidenceUpper: 940, budgetLimit: 900 },
  { date: '2026-09-13', actualCost: 960, forecastCost: 935, confidenceLower: 900, confidenceUpper: 970, budgetLimit: 900 },
  { date: '2026-09-15', actualCost: 980, forecastCost: 950, confidenceLower: 915, confidenceUpper: 985, budgetLimit: 900 },
  { date: '2026-09-17', actualCost: 1040, forecastCost: 990, confidenceLower: 950, confidenceUpper: 1030, budgetLimit: 900 },
  { date: '2026-09-19', actualCost: 1010, forecastCost: 980, confidenceLower: 940, confidenceUpper: 1020, budgetLimit: 900 },
  { date: '2026-09-21', actualCost: 1080, forecastCost: 1020, confidenceLower: 975, confidenceUpper: 1065, budgetLimit: 900 },
  { date: '2026-09-23', actualCost: 1120, forecastCost: 1050, confidenceLower: 1000, confidenceUpper: 1100, budgetLimit: 900 },
  // Forecast horizon (Prophet predictions)
  { date: '2026-09-25', actualCost: null, forecastCost: 1075, confidenceLower: 1015, confidenceUpper: 1135, budgetLimit: 900 },
  { date: '2026-09-27', actualCost: null, forecastCost: 1090, confidenceLower: 1025, confidenceUpper: 1155, budgetLimit: 900 },
  { date: '2026-09-29', actualCost: null, forecastCost: 1115, confidenceLower: 1045, confidenceUpper: 1185, budgetLimit: 900 },
  { date: '2026-10-01', actualCost: null, forecastCost: 1140, confidenceLower: 1060, confidenceUpper: 1220, budgetLimit: 900 },
  { date: '2026-10-03', actualCost: null, forecastCost: 1160, confidenceLower: 1075, confidenceUpper: 1245, budgetLimit: 900 },
  { date: '2026-10-05', actualCost: null, forecastCost: 1190, confidenceLower: 1095, confidenceUpper: 1285, budgetLimit: 900 },
];

export const mockCostBreakdownServices: CostBreakdownItem[] = [
  { category: 'Service', name: 'Amazon EC2', cost: 11420, changePercent: 12.4, percentage: 46.2 },
  { category: 'Service', name: 'Amazon RDS', cost: 5840, changePercent: -2.1, percentage: 23.7 },
  { category: 'Service', name: 'Amazon EBS & Snapshots', cost: 3290, changePercent: 18.5, percentage: 13.3 },
  { category: 'Service', name: 'Amazon S3 Standard & Glacier', cost: 2150, changePercent: 4.2, percentage: 8.7 },
  { category: 'Service', name: 'AWS Lambda & API Gateway', cost: 1240, changePercent: 28.6, percentage: 5.0 },
  { category: 'Service', name: 'AWS NAT Gateways & Egress', cost: 740, changePercent: 5.1, percentage: 3.1 },
];

export const mockUnitEconomicsMetrics: UnitEconomicsMetric[] = [
  {
    id: 'ue_cost_per_active_user',
    name: 'Cost per Active User (MAU)',
    unitLabel: '$/user',
    currentUnitCost: 0.18,
    predictedUnitCost: 0.14,
    kpiVolume: 137000,
    costGrowthPercent: 8.4,
    kpiGrowthPercent: 24.2,
    efficiencyRatio: 1.48,
    shapFeatures: [
      { feature: 'EC2 AutoScaling Efficiency', impact: 0.42, description: 'High attribution from spot instance utilization' },
      { feature: 'EBS GP2 to GP3 Migration', impact: 0.28, description: 'Reduced baseline disk storage costs' },
      { feature: 'Unused NAT Gateway Egress', impact: -0.18, description: 'Suboptimal cross-AZ traffic routing' },
      { feature: 'Idle Staging DB Clusters', impact: -0.12, description: 'Unscaled staging RDS running 24/7' },
    ],
  },
  {
    id: 'ue_cost_per_api_request',
    name: 'Cost per 1M API Requests',
    unitLabel: '$/1M requests',
    currentUnitCost: 1.42,
    predictedUnitCost: 1.15,
    kpiVolume: 17400000,
    costGrowthPercent: 12.1,
    kpiGrowthPercent: 31.5,
    efficiencyRatio: 1.62,
    shapFeatures: [
      { feature: 'Lambda Memory Profiling', impact: 0.38, description: 'Right-sized execution memory allocations' },
      { feature: 'DynamoDB On-Demand Spikes', impact: -0.22, description: 'Unthrottled peak request provisioning' },
      { feature: 'CloudFront Cache Hit Ratio', impact: 0.25, description: 'Improved edge caching strategy' },
    ],
  },
  {
    id: 'ue_cost_per_tenant',
    name: 'Cost per Enterprise Tenant',
    unitLabel: '$/tenant/mo',
    currentUnitCost: 142.50,
    predictedUnitCost: 118.00,
    kpiVolume: 173,
    costGrowthPercent: 4.2,
    kpiGrowthPercent: 18.0,
    efficiencyRatio: 1.76,
    shapFeatures: [
      { feature: 'Multi-tenant Shared DB Clusters', impact: 0.51, description: 'High tenant density per Aurora PostgreSQL instance' },
      { feature: 'Isolated Staging Workloads', impact: -0.29, description: 'Over-provisioned test tenants' },
    ],
  },
];

export const mockCloudResources: CloudResource[] = [
  {
    id: 'res_ec2_i0192a83b',
    resourceId: 'i-094ab2910c83a71b',
    name: 'payment-processing-worker-04',
    service: 'EC2',
    region: 'ap-south-1',
    environment: 'production',
    status: 'underutilized',
    cpuUtilization: 6.2,
    memoryUtilization: 14.5,
    networkIOMbs: 1.2,
    monthlyCost: 384,
    estimatedSaving: 248,
    riskLevel: 'low',
    lastSeen: '1 min ago',
    tags: { Team: 'Payments', Application: 'Checkout', Owner: 'devops-team' },
    metricsHistory: [
      { timestamp: '00:00', cpu: 7.1, memory: 15.0, cost: 384 },
      { timestamp: '04:00', cpu: 4.2, memory: 14.2, cost: 384 },
      { timestamp: '08:00', cpu: 8.5, memory: 14.8, cost: 384 },
      { timestamp: '12:00', cpu: 5.8, memory: 14.1, cost: 384 },
      { timestamp: '16:00', cpu: 6.2, memory: 14.5, cost: 384 },
    ],
  },
  {
    id: 'res_rds_aurora_01',
    resourceId: 'rds-prod-analytics-cluster-01',
    name: 'analytics-warehouse-replica',
    service: 'RDS',
    region: 'ap-south-1',
    environment: 'production',
    status: 'oversized',
    cpuUtilization: 12.4,
    memoryUtilization: 28.0,
    networkIOMbs: 8.5,
    monthlyCost: 1280,
    estimatedSaving: 640,
    riskLevel: 'medium',
    lastSeen: '3 mins ago',
    tags: { Team: 'DataIntelligence', Application: 'Analytics', Owner: 'data-team' },
    metricsHistory: [
      { timestamp: '00:00', cpu: 11.0, memory: 27.5, cost: 1280 },
      { timestamp: '04:00', cpu: 9.8, memory: 27.0, cost: 1280 },
      { timestamp: '08:00', cpu: 14.2, memory: 29.1, cost: 1280 },
      { timestamp: '12:00', cpu: 13.5, memory: 28.4, cost: 1280 },
      { timestamp: '16:00', cpu: 12.4, memory: 28.0, cost: 1280 },
    ],
  },
  {
    id: 'res_ebs_vol_9912',
    resourceId: 'vol-0941fca8291a104',
    name: 'legacy-mongodb-data-disk',
    service: 'EBS',
    region: 'ap-south-1',
    environment: 'production',
    status: 'idle',
    cpuUtilization: 0,
    memoryUtilization: 0,
    networkIOMbs: 0,
    monthlyCost: 215,
    estimatedSaving: 215,
    riskLevel: 'low',
    lastSeen: '10 mins ago',
    tags: { Team: 'Infra', Application: 'LegacyDB', Owner: 'sysadmin' },
    metricsHistory: [
      { timestamp: '00:00', cpu: 0, memory: 0, cost: 215 },
      { timestamp: '16:00', cpu: 0, memory: 0, cost: 215 },
    ],
  },
  {
    id: 'res_nat_gw_02',
    resourceId: 'nat-0a91823f991c28a',
    name: 'vpc-ap-south-1a-nat-gateway',
    service: 'NATGateway',
    region: 'ap-south-1',
    environment: 'production',
    status: 'critical',
    cpuUtilization: 88.4,
    memoryUtilization: 72.0,
    networkIOMbs: 450.0,
    monthlyCost: 940,
    estimatedSaving: 480,
    riskLevel: 'high',
    lastSeen: 'Just now',
    tags: { Team: 'Networking', Application: 'VPC-Egress' },
    metricsHistory: [
      { timestamp: '00:00', cpu: 32.0, memory: 40.0, cost: 440 },
      { timestamp: '08:00', cpu: 65.0, memory: 60.0, cost: 680 },
      { timestamp: '16:00', cpu: 88.4, memory: 72.0, cost: 940 },
    ],
  },
  {
    id: 'res_ec2_i9921b',
    resourceId: 'i-01492a88e9912c4b',
    name: 'ml-training-gpu-node-02',
    service: 'EC2',
    region: 'us-east-1',
    environment: 'staging',
    status: 'idle',
    cpuUtilization: 0.4,
    memoryUtilization: 2.1,
    networkIOMbs: 0.05,
    monthlyCost: 890,
    estimatedSaving: 890,
    riskLevel: 'low',
    lastSeen: '4 mins ago',
    tags: { Team: 'DataScience', Application: 'ML-Train' },
    metricsHistory: [
      { timestamp: '00:00', cpu: 0.5, memory: 2.1, cost: 890 },
      { timestamp: '16:00', cpu: 0.4, memory: 2.1, cost: 890 },
    ],
  },
];

export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec_ec2_resize_0192',
    title: 'Downsize Over-provisioned EC2 Instance (c5.4xlarge → c5.xlarge)',
    resourceId: 'i-094ab2910c83a71b',
    resourceName: 'payment-processing-worker-04',
    service: 'EC2',
    problem: 'Instance operating at an average CPU utilization of 6.2% over the last 30 consecutive days.',
    rootCause: 'Provisioned for peak Black Friday traffic volumes but never scaled down post-event.',
    aiConfidence: 0.94,
    risk: 'low',
    monthlySavings: 248,
    annualSavings: 2976,
    businessImpact: 'Zero risk to transaction response latency based on 90-day workload trace simulation.',
    performanceImpact: 'Peak expected CPU load post-resize is 34.8%, safely below 70% threshold.',
    recommendedAction: 'Apply AWS EC2 instance type modify API call via Boto3 to switch instance type from c5.4xlarge to c5.xlarge during maintenance window.',
    rollbackAction: 'Revert instance type back to c5.4xlarge using AWS Boto3 EC2 client.',
    status: 'needs_review',
    createdAt: '2026-09-22 14:32:00',
    shapFeatures: [
      { feature: '30-Day Mean CPU Utilization (6.2%)', impact: 0.52, description: 'Dominant driver for downsize recommendation' },
      { feature: 'Memory Allocation Threshold (<15%)', impact: 0.31, description: 'RAM usage safely fits smaller instance tier' },
      { feature: 'Network IO Saturation (1.2 Mbps)', impact: 0.12, description: 'Minimal network throughput requirements' },
      { feature: 'Workload Variance Stability (σ²=0.04)', impact: 0.05, description: 'Low variance indicates predictable CPU pattern' },
    ],
    evidence: [
      { metric: 'Avg CPU (30d)', value: '6.2%', baseline: 'Target range: 45%-70%' },
      { metric: 'Peak CPU (30d)', value: '18.4%', baseline: 'Max limit: 80%' },
      { metric: 'Memory Usage', value: '3.1 GB / 32 GB', baseline: 'Current allocation: 32 GB' },
      { metric: 'Monthly Cost', value: '$384 / mo', baseline: 'Optimized cost: $136 / mo' },
    ],
  },
  {
    id: 'rec_ebs_gp2_to_gp3',
    title: 'Migrate Unattached EBS Volume to GP3 & Snapshot Archive',
    resourceId: 'vol-0941fca8291a104',
    resourceName: 'legacy-mongodb-data-disk',
    service: 'EBS',
    problem: 'Volume has been detached from any EC2 instance for 42 days with zero read/write IOPS.',
    rootCause: 'Orphaned disk remaining after legacy MongoDB cluster decommissioning.',
    aiConfidence: 0.98,
    risk: 'low',
    monthlySavings: 215,
    annualSavings: 2580,
    businessImpact: 'No impact. Snapshot is created prior to volume deletion to ensure data retention compliance.',
    performanceImpact: 'None. Storage volume is detached.',
    recommendedAction: 'Create EBS snapshot archive `snap-auto-legacy-mongodb-archive` via Boto3, then execute volume delete request.',
    rollbackAction: 'Restore EBS volume from snapshot `snap-auto-legacy-mongodb-archive`.',
    status: 'needs_review',
    createdAt: '2026-09-23 08:15:00',
    shapFeatures: [
      { feature: 'Detached Duration (42 Days)', impact: 0.65, description: 'High confidence zero-access volume' },
      { feature: 'IOPS Activity (0 Read/Write)', impact: 0.28, description: 'Complete inactivity verified across CloudWatch logs' },
    ],
    evidence: [
      { metric: 'Days Unattached', value: '42 Days', baseline: 'Threshold: 7 Days' },
      { metric: 'Total Read/Write IOPS', value: '0', baseline: 'Active volume: >100 IOPS' },
      { metric: 'Size', value: '2,000 GB GP2', baseline: '$0.10/GB/month' },
    ],
  },
  {
    id: 'rec_rds_rightsize_02',
    title: 'Rightsize RDS Aurora Replica (db.r5.2xlarge → db.r5.xlarge)',
    resourceId: 'rds-prod-analytics-cluster-01',
    resourceName: 'analytics-warehouse-replica',
    service: 'RDS',
    problem: 'Aurora read-replica running with 12.4% average CPU utilization during business hours.',
    rootCause: 'Sized symmetrically with primary write node despite receiving only 15% of query volume.',
    aiConfidence: 0.89,
    risk: 'medium',
    monthlySavings: 640,
    annualSavings: 7680,
    businessImpact: 'Minimal risk. Read traffic can temporarily overflow to secondary replica during instance modify.',
    performanceImpact: 'Max query response latency increase projected at +4.2ms under peak load.',
    recommendedAction: 'Trigger graceful RDS read-replica instance modify call via Boto3 client during low traffic window (02:00 UTC).',
    rollbackAction: 'Modify instance class back to db.r5.2xlarge via Boto3 RDS client.',
    status: 'approved',
    createdAt: '2026-09-21 11:00:00',
    shapFeatures: [
      { feature: 'Read Query Throughput (15% of primary)', impact: 0.48, description: 'Replica workload is significantly lighter than primary' },
      { feature: 'Buffer Cache Hit Ratio (99.8%)', impact: 0.35, description: 'Memory overhead remains optimal on db.r5.xlarge' },
      { feature: 'CPU Saturation (12.4%)', impact: 0.17, description: 'Abundant headroom available post-downsize' },
    ],
    evidence: [
      { metric: 'Replica Query Load', value: '1,200 QPS', baseline: 'Max capacity: 15,000 QPS' },
      { metric: 'Avg CPU', value: '12.4%', baseline: 'Threshold: 60%' },
      { metric: 'Monthly Cost', value: '$1,280 / mo', baseline: 'Optimized: $640 / mo' },
    ],
  },
  {
    id: 'rec_nat_gateway_route',
    title: 'Optimize VPC Egress Traffic & Consolidate NAT Gateways',
    resourceId: 'nat-0a91823f991c28a',
    resourceName: 'vpc-ap-south-1a-nat-gateway',
    service: 'NATGateway',
    region: 'ap-south-1',
    problem: 'High cross-AZ egress data processing costs ($0.045/GB) transferring internal S3 traffic over public NAT.',
    rootCause: 'VPC Gateway Endpoint for S3 missing in ap-south-1 subnet routing table.',
    aiConfidence: 0.96,
    risk: 'high',
    monthlySavings: 480,
    annualSavings: 5760,
    businessImpact: 'Positive impact. S3 bandwidth latency will drop by ~60% by routing over internal AWS backbone.',
    performanceImpact: 'Substantial improvement in data transfer speeds.',
    recommendedAction: 'Create AWS VPC S3 Gateway Endpoint and associate with route table `rtb-0941a823b`.',
    rollbackAction: 'Remove VPC Endpoint association from route table.',
    status: 'needs_review',
    createdAt: '2026-09-23 09:30:00',
    shapFeatures: [
      { feature: 'S3 Egress Volume (12.4 TB/mo)', impact: 0.72, description: 'Massive S3 traffic bypassing internal gateway endpoint' },
      { feature: 'Cross-AZ Processing Fees', impact: 0.24, description: 'Avoidable NAT processing surcharge' },
    ],
    evidence: [
      { metric: 'Monthly Egress', value: '12.4 TB', baseline: 'Cost: $558 via NAT' },
      { metric: 'VPC Endpoint Cost', value: '$0 / mo', baseline: 'Free AWS Gateway Endpoint' },
    ],
  },
];

export const mockAnomalies: Anomaly[] = [
  {
    id: 'anom_dow_9912',
    type: 'denial_of_wallet',
    title: 'Potential Denial-of-Wallet (DoW) Activity Detected on Lambda API Routes',
    severity: 'critical',
    confidence: 0.96,
    resourceId: 'res_lambda_api_gw',
    resourceName: 'api-gateway-auth-handler',
    service: 'Lambda',
    region: 'ap-south-1',
    costVelocity: '+$185/hr (Baseline: $4.20/hr)',
    requestRateChange: '+1,420% Request Spike',
    provisioningSpike: 'Concurrent Executions: 850 / 1000',
    detectedAt: '2026-09-23 09:42:15 UTC',
    status: 'investigating',
    evidence: [
      'Isolation Forest anomaly score: -0.842 (Extreme outlier threshold)',
      '14,200 requests/min originating from distributed proxy IP ranges hitting un-cached `/auth/token` endpoint',
      'Cost velocity projected at $4,440/day if unmitigated',
      'Concurrency limit near saturation, threatening noisy-neighbor degradation',
    ],
    attackTimeline: [
      { step: 'Spike Ingestion', timestamp: '09:38:00', status: 'completed', description: 'Request rate rose from 800 req/min to 14,200 req/min' },
      { step: 'Isolation Forest Flag', timestamp: '09:42:15', status: 'completed', description: 'AI Engine identified cost velocity anomaly with 96% confidence' },
      { step: 'Alert Broadcast', timestamp: '09:42:20', status: 'completed', description: 'Triggered PagerDuty and Slack FinOps SecOps channels' },
      { step: 'Automated Rate-Limit Prep', timestamp: '09:43:00', status: 'current', description: 'CloudSense AI prepared WAF IP throttling policy for approval' },
      { step: 'Mitigation Confirmation', timestamp: 'Pending', status: 'pending', description: 'Awaiting human administrator sign-off to execute AWS WAF rule update via Boto3' },
    ],
  },
  {
    id: 'anom_ec2_provision_spike',
    type: 'cost_anomaly',
    title: 'Abnormal EC2 On-Demand Provisioning Spike in Staging Region',
    severity: 'high',
    confidence: 0.88,
    resourceId: 'res_ec2_i9921b',
    resourceName: 'aws-staging-auto-scaling-group-02',
    service: 'EC2',
    region: 'us-east-1',
    costVelocity: '+$64/hr',
    requestRateChange: '+340% Instance Count',
    provisioningSpike: '12 x p3.8xlarge GPU instances launched',
    detectedAt: '2026-09-23 07:15:00 UTC',
    status: 'detected',
    evidence: [
      'Unscheduled Auto Scaling Group scaling event launched 12 high-cost p3.8xlarge GPU nodes',
      'No CI/CD integration job recorded in correlation timeline',
      'Isolation Forest score: -0.710',
    ],
    attackTimeline: [
      { step: 'Instance Launch', timestamp: '07:10:00', status: 'completed', description: '12 p3.8xlarge nodes requested in us-east-1' },
      { step: 'Anomaly Flagged', timestamp: '07:15:00', status: 'completed', description: 'CloudSense AI detected un-budgeted compute spike' },
      { step: 'Investigation Open', timestamp: '07:16:00', status: 'current', description: 'Awaiting engineer review of rogue test script' },
    ],
  },
];

export const mockRemediationJobs: RemediationJob[] = [
  {
    id: 'rem_job_99120',
    recommendationId: 'rec_rds_rightsize_02',
    actionName: 'Modify RDS Instance Class (db.r5.2xlarge → db.r5.xlarge)',
    resourceId: 'rds-prod-analytics-cluster-01',
    resourceName: 'analytics-warehouse-replica',
    requestedBy: 'Alex Rivera (FinOps)',
    approvedBy: 'Sarah Chen (Lead Cloud Admin)',
    status: 'completed',
    executionId: 'exec_mcp_boto3_88192a',
    startedAt: '2026-09-22 02:00:10 UTC',
    completedAt: '2026-09-22 02:04:45 UTC',
    resultSummary: 'RDS Read-Replica instance successfully modified via Boto3. CloudWatch metrics verify 100% health & expected memory allocation.',
    executionTimeline: [
      { step: 'Recommendation Raised', agent: 'CloudSense AI Engine', timestamp: '2026-09-21 11:00:00', status: 'success', detail: 'Generated recommendation with 89% AI confidence' },
      { step: 'Human Sign-off', agent: 'Governance Center', timestamp: '2026-09-21 14:20:00', status: 'success', detail: 'Approved by Sarah Chen (Lead Cloud Admin)' },
      { step: 'MCP Dispatch', agent: 'CloudSense MCP Client', timestamp: '2026-09-22 02:00:10', status: 'success', detail: 'Secure MCP payload dispatched to Boto3 execution worker' },
      { step: 'AWS Boto3 Execution', agent: 'AWS SDK Boto3 Worker', timestamp: '2026-09-22 02:00:15', status: 'success', detail: 'Called modify_db_instance(DBInstanceIdentifier="analytics-warehouse-replica", DBInstanceClass="db.r5.xlarge", ApplyImmediately=True)' },
      { step: 'Post-Remediation Check', agent: 'Verification Engine', timestamp: '2026-09-22 02:04:45', status: 'success', detail: 'Verified instance status = "available" and CPU load = 22.1%' },
      { step: 'Audit Log Entry', agent: 'Governance Auditor', timestamp: '2026-09-22 02:04:50', status: 'success', detail: 'Logged immutable execution record `evt_88192a`' },
    ],
  },
  {
    id: 'rem_job_99121',
    recommendationId: 'rec_ec2_resize_0192',
    actionName: 'Modify EC2 Instance Type (c5.4xlarge → c5.xlarge)',
    resourceId: 'i-094ab2910c83a71b',
    resourceName: 'payment-processing-worker-04',
    requestedBy: 'Alex Rivera (FinOps)',
    approvedBy: 'Pending Admin Sign-off',
    status: 'pending',
    executionId: 'exec_mcp_boto3_pending',
    startedAt: 'Awaiting Approval',
    resultSummary: 'Pending administrator approval. Expected monthly savings: $248/mo.',
    executionTimeline: [
      { step: 'Recommendation Raised', agent: 'CloudSense AI Engine', timestamp: '2026-09-22 14:32:00', status: 'success', detail: 'Generated recommendation with 94% confidence' },
      { step: 'Human Sign-off', agent: 'Governance Center', timestamp: 'Pending', status: 'pending', detail: 'Awaiting approval from Cloud Administrator' },
    ],
  },
];

export const mockApprovalItems: ApprovalItem[] = [
  {
    id: 'app_9912',
    recommendationId: 'rec_ec2_resize_0192',
    title: 'Downsize EC2 i-094ab2910c83a71b (c5.4xlarge → c5.xlarge)',
    resourceId: 'i-094ab2910c83a71b',
    resourceName: 'payment-processing-worker-04',
    risk: 'low',
    estimatedSavings: 248,
    requester: 'Alex Rivera (FinOps)',
    requestedAt: '2026-09-22 14:35:00 UTC',
    expiresAt: '2026-09-25 14:35:00 UTC',
    status: 'pending',
    evidenceSummary: 'Average CPU utilization is 6.2% over 30 days. Downsizing saves $248/month with zero operational risk.',
  },
  {
    id: 'app_9913',
    recommendationId: 'rec_ebs_gp2_to_gp3',
    title: 'Delete Unattached Orphan EBS Volume vol-0941fca8291a104',
    resourceId: 'vol-0941fca8291a104',
    resourceName: 'legacy-mongodb-data-disk',
    risk: 'low',
    estimatedSavings: 215,
    requester: 'Alex Rivera (FinOps)',
    requestedAt: '2026-09-23 08:20:00 UTC',
    expiresAt: '2026-09-26 08:20:00 UTC',
    status: 'pending',
    evidenceSummary: 'Volume unattached for 42 days. Automated snapshot archive will be created prior to deletion.',
  },
  {
    id: 'app_9914',
    recommendationId: 'rec_nat_gateway_route',
    title: 'Add VPC Gateway Endpoint for S3 & Route Egress Traffic',
    resourceId: 'nat-0a91823f991c28a',
    resourceName: 'vpc-ap-south-1a-nat-gateway',
    risk: 'high',
    estimatedSavings: 480,
    requester: 'CloudSense Automated AI Engine',
    requestedAt: '2026-09-23 09:35:00 UTC',
    expiresAt: '2026-09-24 09:35:00 UTC',
    status: 'pending',
    evidenceSummary: 'Avoids 12.4 TB of S3 egress data traversing public NAT. Reduces NAT charge by $480/month.',
  },
];

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'evt_9901',
    timestamp: '2026-09-23 09:42:20 UTC',
    actor: 'CloudSense Isolation Forest Engine',
    actorRole: 'admin',
    action: 'ANOMALY_DETECTED',
    resourceId: 'api-gateway-auth-handler',
    environment: 'production',
    result: 'warning',
    correlationId: 'corr_dow_88912',
    details: 'Flagged potential Denial-of-Wallet attack with 96% AI confidence (-0.842 score).',
  },
  {
    id: 'evt_9902',
    timestamp: '2026-09-22 14:32:00 UTC',
    actor: 'Alex Rivera',
    actorRole: 'finops_analyst',
    action: 'APPROVAL_REQUESTED',
    resourceId: 'i-094ab2910c83a71b',
    environment: 'production',
    result: 'success',
    correlationId: 'corr_app_9912',
    details: 'Requested approval to downsize EC2 payment processing instance.',
  },
  {
    id: 'evt_9903',
    timestamp: '2026-09-22 02:04:45 UTC',
    actor: 'CloudSense MCP Execution Worker',
    actorRole: 'admin',
    action: 'REMEDIATION_EXECUTED',
    resourceId: 'analytics-warehouse-replica',
    environment: 'production',
    result: 'success',
    correlationId: 'corr_exec_88192a',
    details: 'Executed RDS modify via Boto3 SDK. New class: db.r5.xlarge. Verified state: AVAILABLE.',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif_01',
    type: 'dow',
    title: 'CRITICAL: Potential Denial-of-Wallet (DoW) Detected',
    description: 'Lambda `/auth/token` experiencing +1,420% request surge with cost velocity +$185/hr.',
    severity: 'critical',
    timestamp: '15 minutes ago',
    read: false,
    relatedResourceId: 'res_lambda_api_gw',
    link: '/anomalies/anom_dow_9912',
  },
  {
    id: 'notif_02',
    type: 'approval',
    title: 'Pending Approval: Downsize EC2 Instance c5.4xlarge',
    description: 'Alex Rivera submitted a recommendation review for payment-processing-worker-04 ($248/mo savings).',
    severity: 'medium',
    timestamp: '2 hours ago',
    read: false,
    relatedResourceId: 'i-094ab2910c83a71b',
    link: '/approvals',
  },
  {
    id: 'notif_03',
    type: 'remediation',
    title: 'Remediation Succeeded: RDS Read-Replica Rightsized',
    description: 'Successfully modified analytics-warehouse-replica to db.r5.xlarge. Monthly savings: $640.',
    severity: 'low',
    timestamp: 'Yesterday at 02:04 UTC',
    read: true,
    relatedResourceId: 'rds-prod-analytics-cluster-01',
    link: '/remediation/rem_job_99120',
  },
  {
    id: 'notif_04',
    type: 'forecast',
    title: 'Prophet Model Warning: Projected Budget Overrun',
    description: 'Production AWS spend forecasted to reach $29,120 by month-end, exceeding $25,000 threshold.',
    severity: 'high',
    timestamp: 'Yesterday at 18:30 UTC',
    read: true,
    link: '/cost',
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: 'int_slack_finops',
    name: 'Slack FinOps & SecOps Channel',
    type: 'slack',
    status: 'connected',
    iconName: 'MessageSquare',
    description: 'Real-time alert notifications for cost anomalies, DoW events, and approval requests.',
    lastEventAt: '15 mins ago',
    webhookUrl: 'https://hooks.slack.com/services/placeholder_team/placeholder_channel/placeholder_token',
  },
  {
    id: 'int_teams_ops',
    name: 'Microsoft Teams Cloud Ops',
    type: 'teams',
    status: 'connected',
    iconName: 'Users',
    description: 'Sends weekly FinOps summaries and high-priority recommendation digests to engineering leaders.',
    lastEventAt: '2 hours ago',
    webhookUrl: 'https://outlook.office.com/webhook/xxxxxx-xxxx-xxxx-xxxx/IncomingWebhook/xxxx',
  },
  {
    id: 'int_pagerduty',
    name: 'PagerDuty Incident Escalation',
    type: 'pagerduty',
    status: 'connected',
    iconName: 'AlertTriangle',
    description: 'Triggers high-urgency PagerDuty incidents when Isolation Forest detects severe DoW threats.',
    lastEventAt: '15 mins ago',
  },
  {
    id: 'int_custom_webhook',
    name: 'Enterprise Webhook (Jira / ServiceNow)',
    type: 'webhook',
    status: 'connected',
    iconName: 'Webhook',
    description: 'Custom REST webhook payloads dispatched upon recommendation state changes.',
    lastEventAt: 'Yesterday',
    webhookUrl: 'https://api.enterprise.internal/finops/v1/webhook-receiver',
  },
];

export const mockAssistantInitialMessages: AssistantMessage[] = [
  {
    id: 'msg_01',
    sender: 'assistant',
    text: `Hello Alex! I am **CloudSense AI**, your intelligent cloud resource and FinOps optimization assistant.

I have analyzed your connected AWS environments (**aws-prod-main**, **aws-staging-core**). Here is a quick breakdown of current findings:

- **Potential Monthly Savings:** **$6,840 / mo**
- **Active Anomalies / DoW Alerts:** **1 Critical DoW Alert** on Lambda API Gateway
- **Pending Approvals:** **3 Actions** awaiting governance review

How can I assist you with your cloud environment today?`,
    timestamp: '10:24 AM',
    citations: [
      { label: 'Prophet Cost Forecast', link: '/cost' },
      { label: 'Lambda DoW Alert', link: '/anomalies/anom_dow_9912' },
      { label: 'Recommendations Inbox', link: '/recommendations' },
    ],
  },
];
